// <auto-generated />
using System;
using CharityHub.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CharityHub.Data.Migrations
{
    [DbContext(typeof(CharityHubDbContext))]
    [Migration("20240823131717_updatedatabase1")]
    partial class updatedatabase1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CharityHub.Data.Models.AdminAction", b =>
                {
                    b.Property<Guid>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TargetCampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActionId");

                    b.HasIndex("AdminId");

                    b.HasIndex("TargetCampaignId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("AdminActions");

                    b.HasData(
                        new
                        {
                            ActionId = new Guid("8328c0a5-d539-4fac-a859-c204f671599a"),
                            ActionType = "BanUser",
                            AdminId = new Guid("c86199fc-84e3-423c-9c2b-4853899a5c2a"),
                            CompletedAt = new DateTime(2024, 8, 23, 20, 17, 15, 30, DateTimeKind.Local).AddTicks(1631),
                            TargetCampaignId = new Guid("f98c0fc4-5861-44bb-9ff0-f3537ddde8dd"),
                            TargetUserId = new Guid("d5d2828e-6d1a-4848-9212-076a1c335bbd")
                        });
                });

            modelBuilder.Entity("CharityHub.Data.Models.Campaign", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CampaignCode")
                        .HasColumnType("int");

                    b.Property<string>("CampaignDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CampaignStatus")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("CampaignThumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CampaignTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartnerLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartnerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("CampaignId");

                    b.ToTable("Campaigns");

                    b.HasData(
                        new
                        {
                            CampaignId = new Guid("f98c0fc4-5861-44bb-9ff0-f3537ddde8dd"),
                            CampaignCode = 123,
                            CampaignDescription = "This is a charity campaign.",
                            CampaignStatus = "InProgress",
                            CampaignThumbnail = "path/to/thumbnail.jpg",
                            CampaignTitle = "Charity Campaign",
                            CurrentAmount = 5000.00m,
                            DateCreated = new DateTime(2024, 8, 23, 20, 17, 15, 30, DateTimeKind.Local).AddTicks(1624),
                            EndDate = new DateTime(2024, 9, 23, 20, 17, 15, 30, DateTimeKind.Local).AddTicks(1592),
                            PartnerLogo = "path/to/logo.jpg",
                            PartnerName = "Partner Organization",
                            PartnerNumber = "0987654321",
                            StartDate = new DateTime(2024, 8, 23, 20, 17, 15, 30, DateTimeKind.Local).AddTicks(1576),
                            TargetAmount = 10000.00m
                        });
                });

            modelBuilder.Entity("CharityHub.Data.Models.Donation", b =>
                {
                    b.Property<Guid>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDonated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirm")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DonationId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("UserId");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            DonationId = new Guid("57d2bc11-6602-4189-bcbb-02d8bfddc264"),
                            Amount = 100.00m,
                            CampaignId = new Guid("f98c0fc4-5861-44bb-9ff0-f3537ddde8dd"),
                            DateDonated = new DateTime(2024, 8, 23, 20, 17, 15, 30, DateTimeKind.Local).AddTicks(1636),
                            IsConfirm = true,
                            PaymentMethod = "Paypal",
                            UserId = new Guid("d5d2828e-6d1a-4848-9212-076a1c335bbd")
                        });
                });

            modelBuilder.Entity("CharityHub.Data.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5248787c-15cf-4ba5-ba51-de21b6960234"),
                            ConcurrencyStamp = "6ba99203-aeea-4676-b9b7-204bd186e8c9",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = new Guid("6ba99203-aeea-4676-b9b7-204bd186e8c9"),
                            ConcurrencyStamp = "6ba99203-aeea-4676-b9b7-204bd186e8c9",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("CharityHub.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d5d2828e-6d1a-4848-9212-076a1c335bbd"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "46647781-482e-4e66-98aa-a4e3b28e079b",
                            DateCreated = new DateTime(2024, 8, 23, 20, 17, 14, 597, DateTimeKind.Local).AddTicks(8700),
                            DisplayName = "Datdq",
                            Email = "datdq@gmail.com",
                            EmailConfirmed = false,
                            IsActive = true,
                            LastLoginDate = new DateTime(2024, 8, 23, 20, 17, 14, 597, DateTimeKind.Local).AddTicks(8720),
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEPHZopHzB3wHn1eluZPDLycTM2FPlfGpeNclaG+ZgHl+TCZ51l8yjY/xNOBG04ENSg==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "datdq@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("c86199fc-84e3-423c-9c2b-4853899a5c2a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ec639297-3809-4e07-adb6-c3d8788cf1c5",
                            DateCreated = new DateTime(2024, 8, 23, 20, 17, 14, 832, DateTimeKind.Local).AddTicks(1485),
                            DisplayName = "Anv",
                            Email = "Anv@gmail.com",
                            EmailConfirmed = false,
                            IsActive = true,
                            LastLoginDate = new DateTime(2024, 8, 23, 20, 17, 14, 832, DateTimeKind.Local).AddTicks(1506),
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEGKTNdQluM8RNFz2fbC6juYOW0ipiU7QS77aX+OaNa9JPodWbbWALfIC+CBbILIefg==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Anv@gmail.com"
                        });
                });

            modelBuilder.Entity("CharityHub.Data.Models.UserFollows", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateFollowed")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "CampaignId");

                    b.HasIndex("CampaignId");

                    b.ToTable("UserFollows");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("d5d2828e-6d1a-4848-9212-076a1c335bbd"),
                            CampaignId = new Guid("f98c0fc4-5861-44bb-9ff0-f3537ddde8dd"),
                            DateFollowed = new DateTime(2024, 8, 23, 20, 17, 15, 30, DateTimeKind.Local).AddTicks(1642),
                            IsNotified = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("d5d2828e-6d1a-4848-9212-076a1c335bbd"),
                            RoleId = new Guid("5248787c-15cf-4ba5-ba51-de21b6960234")
                        },
                        new
                        {
                            UserId = new Guid("c86199fc-84e3-423c-9c2b-4853899a5c2a"),
                            RoleId = new Guid("6ba99203-aeea-4676-b9b7-204bd186e8c9")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CharityHub.Data.Models.AdminAction", b =>
                {
                    b.HasOne("CharityHub.Data.Models.User", "Admin")
                        .WithMany("AdminActions")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CharityHub.Data.Models.Campaign", "TargetCampaign")
                        .WithMany("AdminActions")
                        .HasForeignKey("TargetCampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CharityHub.Data.Models.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Admin");

                    b.Navigation("TargetCampaign");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("CharityHub.Data.Models.Donation", b =>
                {
                    b.HasOne("CharityHub.Data.Models.Campaign", "Campaign")
                        .WithMany("Donations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharityHub.Data.Models.User", "User")
                        .WithMany("Donations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CharityHub.Data.Models.UserFollows", b =>
                {
                    b.HasOne("CharityHub.Data.Models.Campaign", "Campaign")
                        .WithMany("UserFollows")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharityHub.Data.Models.User", "User")
                        .WithMany("UserFollows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CharityHub.Data.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CharityHub.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CharityHub.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("CharityHub.Data.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharityHub.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CharityHub.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharityHub.Data.Models.Campaign", b =>
                {
                    b.Navigation("AdminActions");

                    b.Navigation("Donations");

                    b.Navigation("UserFollows");
                });

            modelBuilder.Entity("CharityHub.Data.Models.User", b =>
                {
                    b.Navigation("AdminActions");

                    b.Navigation("Donations");

                    b.Navigation("UserFollows");
                });
#pragma warning restore 612, 618
        }
    }
}
