// <auto-generated />
using System;
using CharityHub.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CharityHub.Data.Migrations
{
    [DbContext(typeof(CharityHubDbContext))]
    [Migration("20240821090637_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CharityHub.Data.Models.AdminAction", b =>
                {
                    b.Property<Guid>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TargetCampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActionId");

                    b.HasIndex("AdminId");

                    b.HasIndex("TargetCampaignId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("AdminActions");

                    b.HasData(
                        new
                        {
                            ActionId = new Guid("5c197a0c-d433-4718-89a9-7bbb8c4c8c5a"),
                            ActionType = "BanUser",
                            AdminId = new Guid("6e168ab2-f753-42e3-a7fa-52c1389503bf"),
                            CompletedAt = new DateTime(2024, 8, 21, 16, 6, 37, 537, DateTimeKind.Local).AddTicks(4329),
                            TargetCampaignId = new Guid("a90c326f-edd2-462e-8080-2b97fd932021"),
                            TargetUserId = new Guid("e42e1e51-1b1c-4a09-864c-6675b4ff119c")
                        });
                });

            modelBuilder.Entity("CharityHub.Data.Models.Campaign", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CampaignCode")
                        .HasColumnType("int");

                    b.Property<string>("CampaignDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CampaignStatus")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("CampaignThumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("CampaignTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartnerLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartnerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("CampaignId");

                    b.ToTable("Campaigns");

                    b.HasData(
                        new
                        {
                            CampaignId = new Guid("a90c326f-edd2-462e-8080-2b97fd932021"),
                            CampaignCode = 123,
                            CampaignDescription = "This is a charity campaign.",
                            CampaignStatus = "InProgress",
                            CampaignThumbnail = "path/to/thumbnail.jpg",
                            CampaignTitle = "Charity Campaign",
                            CurrentAmount = 5000.00m,
                            DateCreated = new DateTime(2024, 8, 21, 16, 6, 37, 537, DateTimeKind.Local).AddTicks(4328),
                            EndDate = new DateTime(2024, 9, 21, 16, 6, 37, 537, DateTimeKind.Local).AddTicks(4279),
                            PartnerLogo = "path/to/logo.jpg",
                            PartnerName = "Partner Organization",
                            PartnerNumber = "0987654321",
                            StartDate = new DateTime(2024, 8, 21, 16, 6, 37, 537, DateTimeKind.Local).AddTicks(4267),
                            TargetAmount = 10000.00m
                        });
                });

            modelBuilder.Entity("CharityHub.Data.Models.Donation", b =>
                {
                    b.Property<Guid>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDonated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirm")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DonationId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("UserId");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            DonationId = new Guid("619e3f80-bafb-48f9-9fc8-6656f4eab17e"),
                            Amount = 100.00m,
                            CampaignId = new Guid("a90c326f-edd2-462e-8080-2b97fd932021"),
                            DateDonated = new DateTime(2024, 8, 21, 16, 6, 37, 537, DateTimeKind.Local).AddTicks(4332),
                            IsConfirm = true,
                            PaymentMethod = "Paypal",
                            UserId = new Guid("e42e1e51-1b1c-4a09-864c-6675b4ff119c")
                        });
                });

            modelBuilder.Entity("CharityHub.Data.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1690b49-4678-4ef4-98d8-3092defa7acb"),
                            Name = "User"
                        },
                        new
                        {
                            Id = new Guid("0be6e455-f445-4bb0-b7d5-5adc8e84722f"),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("CharityHub.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e42e1e51-1b1c-4a09-864c-6675b4ff119c"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "044b4d8f-3a04-4387-a8f1-8068272c8f1a",
                            DateCreated = new DateTime(2024, 8, 21, 16, 6, 37, 427, DateTimeKind.Local).AddTicks(5459),
                            Email = "datdq@gmail.com",
                            EmailConfirmed = false,
                            IsActive = true,
                            LastLoginDate = new DateTime(2024, 8, 21, 16, 6, 37, 427, DateTimeKind.Local).AddTicks(5471),
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEBQKxM2Y6d38j0Zbjf+VVAXGhZSR5x2nJit2RfPqDPkEiJsFDJqr2VsYj2E1rR35xQ==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "datdq@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("6e168ab2-f753-42e3-a7fa-52c1389503bf"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c4290150-a6a3-43c5-be93-6d2a267a020c",
                            DateCreated = new DateTime(2024, 8, 21, 16, 6, 37, 483, DateTimeKind.Local).AddTicks(662),
                            Email = "Anv@gmail.com",
                            EmailConfirmed = false,
                            IsActive = true,
                            LastLoginDate = new DateTime(2024, 8, 21, 16, 6, 37, 483, DateTimeKind.Local).AddTicks(678),
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEP3bCVIDpZsmtTd2rw6zfCb20GXnSsc4+F2MPGT7ury0zjKHpvzkdGeOY5sY6gi69Q==",
                            PhoneNumber = "0987654321",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Anv@gmail.com"
                        });
                });

            modelBuilder.Entity("CharityHub.Data.Models.UserFollows", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateFollowed")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "CampaignId");

                    b.HasIndex("CampaignId");

                    b.ToTable("UserFollows");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e42e1e51-1b1c-4a09-864c-6675b4ff119c"),
                            CampaignId = new Guid("a90c326f-edd2-462e-8080-2b97fd932021"),
                            DateFollowed = new DateTime(2024, 8, 21, 16, 6, 37, 537, DateTimeKind.Local).AddTicks(4334),
                            IsNotified = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e42e1e51-1b1c-4a09-864c-6675b4ff119c"),
                            RoleId = new Guid("c1690b49-4678-4ef4-98d8-3092defa7acb")
                        },
                        new
                        {
                            UserId = new Guid("6e168ab2-f753-42e3-a7fa-52c1389503bf"),
                            RoleId = new Guid("0be6e455-f445-4bb0-b7d5-5adc8e84722f")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CharityHub.Data.Models.AdminAction", b =>
                {
                    b.HasOne("CharityHub.Data.Models.User", "Admin")
                        .WithMany("AdminActions")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CharityHub.Data.Models.Campaign", "TargetCampaign")
                        .WithMany("AdminActions")
                        .HasForeignKey("TargetCampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CharityHub.Data.Models.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Admin");

                    b.Navigation("TargetCampaign");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("CharityHub.Data.Models.Donation", b =>
                {
                    b.HasOne("CharityHub.Data.Models.Campaign", "Campaign")
                        .WithMany("Donations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharityHub.Data.Models.User", "User")
                        .WithMany("Donations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CharityHub.Data.Models.UserFollows", b =>
                {
                    b.HasOne("CharityHub.Data.Models.Campaign", "Campaign")
                        .WithMany("UserFollows")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharityHub.Data.Models.User", "User")
                        .WithMany("UserFollows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CharityHub.Data.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CharityHub.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CharityHub.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("CharityHub.Data.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharityHub.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CharityHub.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharityHub.Data.Models.Campaign", b =>
                {
                    b.Navigation("AdminActions");

                    b.Navigation("Donations");

                    b.Navigation("UserFollows");
                });

            modelBuilder.Entity("CharityHub.Data.Models.User", b =>
                {
                    b.Navigation("AdminActions");

                    b.Navigation("Donations");

                    b.Navigation("UserFollows");
                });
#pragma warning restore 612, 618
        }
    }
}
